ARG VERSION
ARG LDFLAGS
FROM golang:1.14-stretch as builder
ENV CGO_ENABLED=1
ENV GOPATH=/go
ADD . /go/src/github.com/wutong-paas/cloud-adaptor/
WORKDIR /go/src/github.com/wutong-paas/cloud-adaptor/
ENV GOPROXY=https://goproxy.io
RUN go build -ldflags "$LDFLAGS" -o /cloud-adaptor


# FROM wutongpaas/wutong:$VERSION-allinone
# COPY --from=builder /go/src/github.com/wutong-paas/cloud-adaptor/chart /app/chart
# COPY --from=builder /cloud-adaptor /app/cloudadaptor