apiVersion: apps/v1
kind: Deployment
metadata:
  name: wutong-operator
  namespace: wt-system
  labels:
    control-plane: wutong-operator
spec:
  selector:
    matchLabels:
      control-plane: wutong-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: wutong-operator
    spec:
      serviceAccountName: wutong-operator
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run
            type: Directory
      containers:
        - command:
            - /manager
          args:
            - --leader-elect
            - --zap-log-level=4
          image: swr.cn-southwest-2.myhuaweicloud.com/wutong/wutong-operator:v1.0.0-stable
          imagePullPolicy: IfNotPresent
          name: wutong-operator
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - mountPath: /var/run
              name: dockersock
      terminationGracePeriodSeconds: 10
