name: release-ci-build

on:
  release:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: swr.cn-southwest-2.myhuaweicloud.com
          username: ${{ secrets.DOMESTIC_DOCKER_USERNAME }}
          password: ${{ secrets.DOMESTIC_DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: Dockerfile
          tags: swr.cn-southwest-2.myhuaweicloud.com/wutong/wutong-adaptor:v1.0.0-stable
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
